### ISSUE TITLE
Missing powermenu.sh

### ISSUE THREAD

**Issue by Koschi13** [HeinzDev/Hyprland-dotfiles#3]
First, thanks for sharing this awesome config. I was using it to inspire my very first NixOs setup.

In https://github.com/HeinzDev/Hyprland-dotfiles/blob/main/home/programs/waybar/default.nix you have the following [line](https://github.com/HeinzDev/Hyprland-dotfiles/blob/main/home/programs/waybar/default.nix#L222):
```nix
          "on-click" = "pkill rofi || ~/.config/rofi/powermenu/type-3/powermenu.sh";
```

But I can't find the script in https://github.com/HeinzDev/Hyprland-dotfiles/blob/main/home/scripts/default.nix

Could you maybe provide it to us?

**Comment by HeinzDev** [comment]
Sorry for the inconvenience my friend! The missing script is from the famous Rofi Theme Repository [Rofi Themes](https://github.com/adi1090x/rofi)
