### ISSUE TITLE
cava-internal

### ISSUE THREAD

**Issue by Gxnum** [HeinzDev/Hyprland-dotfiles#5]
Hello! I clicked on your dotfiles to see how you integrated cava in waybar. Looking at `home/scripts/default.nix` I saw that `cava-internal` is `cava -p ~/.config/cava/config1 | sed -u 's/;//g;s/0/▁/g;s/1/▂/g;s/2/▃/g;s/3/▄/g;s/4/▅/g;s/5/▆/g;s/6/▇/g;s/7/█/g;'`. Where can I find `~/.config/cava/config1`? If it isn't in your dotfiles and if you don't mind, please share me the config file. Thanks!

**Comment by HeinzDev** [comment]
Hi there! The difference between the config and config1 are minimal, i'll leave a link with[ both files](https://drive.google.com/drive/folders/1wRK-1jKvjmZbxk8gBP9Ll3_urnKm9jCw?usp=sharing) and list them config1 changes below:

```
- bars = 12
- ascii_max_range = 7
- sleep_timer = 10
- method = raw
- data_format = ascii
- ascii_max_range = 7
- [No gradient color added]
```
You can use the home manager to add those files in your config but as you can see it's fully optional.
